package com.dodo.api.models;
// Generated Oct 9, 2023, 11:00:28 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Orderdetail generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "orderdetail")
public class Orderdetail implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orderdetailid", unique = true, nullable = false)
	private Integer orderDetailId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderid")
	private Order order;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid")
	private Product product;

	@Column(name = "quantity")
	private Integer quantity;

	@Column(name = "unitprice", precision = 10)
	private Double unitPrice;

	@Column(name = "subtotal", precision = 10)
	private Double subtotal;

	@Column(name = "productname")
	private String productName;

	@Column(name = "productdescription", length = 65535)
	private String productDescription;

	@Column(name = "productimage")
	private String productImage;
	
	@Column(name = "isreviewed")
	private Boolean isReviewed;


}
