package com.dodo.api.models;
// Generated Oct 9, 2023, 11:00:28 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review")
public class Review implements java.io.Serializable {

	private Integer reviewId;
	private Product product;
	private User user;
	private Integer rating;
	private String comment;
	private Date reviewDate;
	private Integer helpfulCount;
	private Integer reportCount;
	private Boolean isVerified;
	private Date createdAt;
	private Date updatedAt;
	private Orderdetail orderdetails;
	private String reviewImage;
	

	public Review() {
	}

	public Review(Product product, User user, Integer rating, String comment, Date reviewDate, Integer helpfulCount,
			Integer reportCount, Boolean isVerified, Date createdAt, Date updatedAt, Orderdetail orderdetails, String reviewImage) {
		this.product = product;
		this.user = user;
		this.rating = rating;
		this.comment = comment;
		this.reviewDate = reviewDate;
		this.helpfulCount = helpfulCount;
		this.reportCount = reportCount;
		this.isVerified = isVerified;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.orderdetails = orderdetails;
		this.reviewImage = reviewImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "reviewid", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	@Column(name = "comment", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reviewdate", length = 10)
	public Date getReviewDate() {
		return this.reviewDate;
	}

	public void setReviewDate(Date reviewDate) {
		this.reviewDate = reviewDate;
	}

	@Column(name = "helpfulcount")
	public Integer getHelpfulCount() {
		return this.helpfulCount;
	}

	public void setHelpfulCount(Integer helpfulCount) {
		this.helpfulCount = helpfulCount;
	}

	@Column(name = "reportcount")
	public Integer getReportCount() {
		return this.reportCount;
	}

	public void setReportCount(Integer reportCount) {
		this.reportCount = reportCount;
	}

	@Column(name = "isverified")
	public Boolean getIsVerified() {
		return this.isVerified;
	}

	public void setIsVerified(Boolean isVerified) {
		this.isVerified = isVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdat", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedat", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderdetailid")
	public Orderdetail getOrderDetail() {
		return this.orderdetails;
	}

	public void setOrderDetail(Orderdetail orderdetails) {
		this.orderdetails = orderdetails;
	}
	
	@Column(name = "reviewimage")
	public String getReviewImage() {
		return this.reviewImage;
	}

	public void setReviewImage(String reviewImage) {
		this.reviewImage = reviewImage;
	}
}
