package com.dodo.web.models;
// Generated Oct 9, 2023, 11:00:28 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Category generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "category")
public class Category implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "categoryid", unique = true, nullable = false)
	private Integer categoryId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentcategoryid")
	private Parentcategory parentcategory;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	private User user;
	
	@Column(name = "categoryname")
	@NotBlank(message = "Category name must not be blank")
	private String categoryName;	
	
	@Column(name = "description", length = 65535)
	private String description;
	
	@Column(name = "imagepath")
	private String imagePath;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdat", length = 19)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date createdAt;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedat", length = 19)
	private Date updatedAt;
	
	@Column(name = "status")
	private Boolean status;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	private Set<Product> products = new HashSet<Product>(0);
	
	@Override
	public String toString() {
		return "Category [categoryId=" + categoryId + ", parentcategory=" + parentcategory.getParentCategoryId() + ", user=" + user.getUserId()
				+ ", categoryName=" + categoryName + ", description=" + description + ", imagePath=" + imagePath
				+ ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + ", status=" + status + "]";
	}

}
