package com.dodo.web.models;
// Generated Oct 9, 2023, 11:00:28 PM by Hibernate Tools 4.3.6.Final

import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * User generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userid", unique = true, nullable = false)
	private Integer userId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleid")
	private Role role;
	
	@Column(name = "username", length = 50)
	@NotBlank
	private String username;
	
	@Column(name = "password")
	private String password;
	
	@Column(name = "email")
	@NotBlank
	private String email;
	
	@Column(name = "firstname", length = 50)
	@NotBlank
	private String firstName;
	
	@Column(name = "lastname", length = 50)
	@NotBlank
	private String lastName;
	
	@Column(name = "address")
	@NotBlank
	private String address;
	
	@Column(name = "phonenumber", length = 20)
	@NotBlank
	private String phoneNumber;
	
	@Column(name = "avatar")
	private String avatar;
	
	@Column(name = "gender")
	private String gender;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	@NotNull
	private Date dob;
	
	@Column(name = "status")
	private Boolean status;
	
	@Column(name = "token")
	private String token;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdat", length = 19)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date createdAt;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updatedat", length = 19)
	@DateTimeFormat(pattern = "dd/MM/yyyy")
	private Date updatedAt;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Shopowner> shopowners = new HashSet<Shopowner>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Salesdata> salesdatas = new HashSet<Salesdata>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Notification> notifications = new HashSet<Notification>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Order> orders = new HashSet<Order>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Item> items = new HashSet<Item>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Wishlist> wishlists = new HashSet<Wishlist>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Ordercancellation> ordercancellations = new HashSet<Ordercancellation>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Review> reviews = new HashSet<Review>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	private Set<Category> categories = new HashSet<Category>(0);
        
	
	@Override
	public String toString() {
		return "User [userId=" + userId + ", username=" + username + ", password=" + password + ", email=" + email
				+ ", firstName=" + firstName + ", lastName=" + lastName + ", address=" + address + ", phoneNumber="
				+ phoneNumber + ", avatar=" + avatar + ", gender=" + gender + ", dob=" + dob + ", status=" + status
				+ ", token=" + token + ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + "]";
	}

	

	
}
